// flow-typed signature: c93b08c55f4c008097b8ecd1824dc6dc
// flow-typed version: <<STUB>>/pull-defer_v0.2.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pull-defer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pull-defer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pull-defer/duplex' {
  declare module.exports: any;
}

declare module 'pull-defer/sink' {
  declare module.exports: any;
}

declare module 'pull-defer/source' {
  declare module.exports: any;
}

declare module 'pull-defer/test/duplex' {
  declare module.exports: any;
}

declare module 'pull-defer/test/sink' {
  declare module.exports: any;
}

declare module 'pull-defer/test/source' {
  declare module.exports: any;
}

declare module 'pull-defer/test/through' {
  declare module.exports: any;
}

declare module 'pull-defer/through' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pull-defer/duplex.js' {
  declare module.exports: $Exports<'pull-defer/duplex'>;
}
declare module 'pull-defer/index' {
  declare module.exports: $Exports<'pull-defer'>;
}
declare module 'pull-defer/index.js' {
  declare module.exports: $Exports<'pull-defer'>;
}
declare module 'pull-defer/sink.js' {
  declare module.exports: $Exports<'pull-defer/sink'>;
}
declare module 'pull-defer/source.js' {
  declare module.exports: $Exports<'pull-defer/source'>;
}
declare module 'pull-defer/test/duplex.js' {
  declare module.exports: $Exports<'pull-defer/test/duplex'>;
}
declare module 'pull-defer/test/sink.js' {
  declare module.exports: $Exports<'pull-defer/test/sink'>;
}
declare module 'pull-defer/test/source.js' {
  declare module.exports: $Exports<'pull-defer/test/source'>;
}
declare module 'pull-defer/test/through.js' {
  declare module.exports: $Exports<'pull-defer/test/through'>;
}
declare module 'pull-defer/through.js' {
  declare module.exports: $Exports<'pull-defer/through'>;
}
