// flow-typed signature: fa432dbf0bb548494430fe6206dab986
// flow-typed version: <<STUB>>/stand-in_v4.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stand-in'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stand-in' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stand-in/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stand-in/lib/index.js' {
  declare module.exports: $Exports<'stand-in/lib/index'>;
}
